CREATE DATABASE CarRentalManagement
GO

USE CarRentalManagement
GO

CREATE TABLE Customers (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Firstname NVARCHAR(64) NOT NULL,
	Lastname NVARCHAR(128) NOT NULL,
	Pesel NVARCHAR(11) NOT NULL,
	DateOfBirth DATE NOT NULL,
	PlaceOfBirth NVARCHAR(128) NOT NULL,
	IsActive BIT NOT NULL,
	CreationDateTime DATETIME NOT NULL,
	EditDateTime DATETIME NULL,
	DeleteDateTime DATETIME NULL,
);

CREATE TABLE Warnings (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CustomerId INT NOT NULL FOREIGN KEY REFERENCES Customers(Id),
	Description NVARCHAR(MAX) NOT NULL,
	WarningDate DATE NOT NULL,
	IsActive BIT NOT NULL,
	CreationDateTime DATETIME NOT NULL,
	EditDateTime DATETIME NULL,
	DeleteDateTime DATETIME NULL,
);

CREATE TABLE VehicleCategies (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Title NVARCHAR(128) NOT NULL,
	IsActive BIT NOT NULL,
	CreationDateTime DATETIME NOT NULL,
	EditDateTime DATETIME NULL,
	DeleteDateTime DATETIME NULL,
);

CREATE TABLE Vehicles (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Brand NVARCHAR(64) NOT NULL,
	Model NVARCHAR(128) NOT NULL,
	Production INT NOT NULL,
	COLOR NVARCHAR(64) NOT NULL,
	VehicleCategyId INT NOT NULL FOREIGN KEY REFERENCES VehicleCategies(Id),
	IsActive BIT NOT NULL,
	CreationDateTime DATETIME NOT NULL,
	EditDateTime DATETIME NULL,
	DeleteDateTime DATETIME NULL,
);

CREATE TABLE Fuelings (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	VehicleId INT NOT NULL FOREIGN KEY REFERENCES Vehicles(Id),
	FuelingDate DATE NOT NULL,
	Quantity DECIMAL NOT NULL,
	Price MONEY NULL,
	IsActive BIT NOT NULL,
	CreationDateTime DATETIME NOT NULL,
	EditDateTime DATETIME NULL,
	DeleteDateTime DATETIME NULL,
);

CREATE TABLE Insurances (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	VehicleId INT NOT NULL FOREIGN KEY REFERENCES Vehicles(Id),
	BeginDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	IsActive BIT NOT NULL,
	CreationDateTime DATETIME NOT NULL,
	EditDateTime DATETIME NULL,
	DeleteDateTime DATETIME NULL,
);

CREATE TABLE Services (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Title NVARCHAR(MAX) NOT NULL,
	Description NVARCHAR(MAX) NULL,
	IsActive BIT NOT NULL,
	CreationDateTime DATETIME NOT NULL,
	EditDateTime DATETIME NULL,
	DeleteDateTime DATETIME NULL,
);

CREATE TABLE VehicleServices (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	VehicleId INT NOT NULL FOREIGN KEY REFERENCES Vehicles(Id),
	ServiceId INT NOT NULL FOREIGN KEY REFERENCES Services(Id),
	ServiceDate DATE NOT NULL,
	IsActive BIT NOT NULL,
	CreationDateTime DATETIME NOT NULL,
	EditDateTime DATETIME NULL,
	DeleteDateTime DATETIME NULL,
);

CREATE TABLE Rentals (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CustomerId INT NOT NULL FOREIGN KEY REFERENCES Customers(Id),
	VehicleId INT NOT NULL FOREIGN KEY REFERENCES Vehicles(Id),
	BeginDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	IsActive BIT NOT NULL,
	CreationDateTime DATETIME NOT NULL,
	EditDateTime DATETIME NULL,
	DeleteDateTime DATETIME NULL,
);

CREATE TABLE Invoices (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Title NVARCHAR(255) NOT NULL,
	InvoiceDate DATE NOT NULL,
	RentalId INT NOT NULL FOREIGN KEY REFERENCES Rentals(Id),
	Price MONEY NOT NULL,
	IsActive BIT NOT NULL,
	CreationDateTime DATETIME NOT NULL,
	EditDateTime DATETIME NULL,
	DeleteDateTime DATETIME NULL,
);

CREATE TABLE Payments (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PaymentTotal MONEY NOT NULL,
	InvoiceId INT NOT NULL FOREIGN KEY REFERENCES Invoices(Id),
	IsFinalized BIT NOT NULL,
	FinalizationDate DATE NULL,
	IsActive BIT NOT NULL,
	CreationDateTime DATETIME NOT NULL,
	EditDateTime DATETIME NULL,
	DeleteDateTime DATETIME NULL,
);

CREATE TABLE Deposits (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	RentalId INT NOT NULL FOREIGN KEY REFERENCES Rentals(Id),
	Price MONEY NOT NULL,
	Status NVARCHAR(64) NOT NULL,
	IsActive BIT NOT NULL,
	CreationDateTime DATETIME NOT NULL,
	EditDateTime DATETIME NULL,
	DeleteDateTime DATETIME NULL,
);